[package]
name = "llsd"
version = "0.1.0"
authors = ["John-Nagle <nagle@animats.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
quick-xml = "0.22.0"
uuid = { version = "0.8.1", features = ["v4"] }
